### PR TITLE
Fix for #75

### PR DESCRIPTION
**Pull request by LaynePeng**
A fix for "Compile fail, cannot find "tee2metron" in diego release #75 "

### CODE REVIEW

**Comment by LaynePeng** [comment]
Hi, I have sent the application for CLA, but not response. Who I can get in touch for this?

**Comment by onsi** [comment]
HI @LaynePeng - I just checked and your CLA has, indeed, been accepted.  Sorry for the delay in getting back to you.

With that said, we don't think a fix is necessary for the problem you've described.  I'll comment on the issue.

**Comment by LaynePeng** [comment]
Hi, @onsi , No problem, I am happy to have chance to work for Cloud Foundry project. 

And for the issue, I found the problem: it is required to clone Lattice to ~/workspace/diego-release/src/github.com/cloudfoundry-incubator . But why it is nessary? In diego Release, it doesn't depend to Lattice actually (should be Lattice depends Diego, right?). And in the build script, we can simplely get the Lattice path for building. However, as you said, if we did as the guide, it will work.

**Comment by onsi** [comment]
Hey Layne,

Thanks for trying it out.  As you've seen there isn't a lot of code in
Lattice -- it's almost *all* in Diego which has a number of interrelated
components that need to be versioned correctly.  We've found the best way
to do this is with submodules.

Onsi

**Comment by LaynePeng** [comment]
Thanks for analysis, it makes sense. :)

**Pull request closed without merging**
