### PR TITLE
Fix some commands help, some commands  invalid usage error

### PR DESCRIPTION
**Pull request by SrinivasChilveri**
1) help is changed for  ce, task, ct,dt
2) Invalid usage changed for ssh & task

Any suggestions/comments are welcome

### CODE REVIEW

**Comment by davidwadden** [comment]
Hey thanks for submitting this;  we're in the middle of a major refactor and aren't merging PRs at the moment, we'll take a look at this soon though.  I have this prioritized for review before our next release.

If we approve this, do you mind if we rebase the commit?

**Comment by SrinivasChilveri** [comment]
Hi @davidwadden , Its fine. if you want me to rebase & do update the PR also fine.

Thanks & Regards,
SriniCH

**Comment by ekcasey** [comment]
this looks mostly good.   but, we don't use the "_GUID" terminology in Lattice, we call them the `APP_NAME` and `TASK_NAME`, so can you remove the changes to the task_examiner_command_factory and task_runner_command_factory and use TASK_NAME instead of TASK_GUID?

thanks
@davidwadden + @ekcasey

**Comment by SrinivasChilveri** [comment]
Hi @ekcasey  @davidwadden , I have seen the similar things in task cancel,task delete commands.even if we observe the submit task/create task things its task guid not the task name.Even in failure  strings also we had mentioned task_guid not not task name for all task related commands(same is in receptor API description also). If you still want me to change i will change at those two places. please do let me know your opinion.

Thanks & Regards,
SriniCH

**Comment by SrinivasChilveri** [comment]
Hi @ekcasey  @davidwadden , I mean there is inconsistency between description & error messages for task commands(examine,runner).So let me know your inputs on the same.i can keep the error messages with TASK_GUID & in description TASK_NAME ??

Thanks & Regards,
SriniCH

**Comment by davidwadden** [comment]
We apologize here.  We're re-arranging our repositories and Github decided to close out all the PRs when we swapped the branches.

Please go ahead and reopen this against **master** on https://github.com/cloudfoundry-incubator/ltc and we'll consider it.

Give me a bit I'll respond to your question about the error messages here.

**Comment by davidwadden** [comment]
I just reviewed https://github.com/SrinivasChilveri/lattice/commit/8a9b79fc6d76219817061d4a36f0a292e9a30cab -- I see.  You're right.  Let's just keep it consistent with `TASK_GUID`.  Go ahead an re-submit this against https://github.com/cloudfoundry-incubator/ltc and we'll merge it.

**Pull request closed without merging**
