### PR TITLE
Terraform can't deploy because AMI's are outdated

### PR DESCRIPTION
**Pull request by 3h4x**
New AMI's for issue cloudfoundry-incubator/lattice#100
I have used http://cloud-images.ubuntu.com/locator/ec2/ to look up fresh ones

### CODE REVIEW

**Comment by davidwadden** [comment]
@3h4x We're ready to pull this thing in,  do you mind rebasing it up so we can merge?

**Comment by 3h4x** [comment]
great! i'm on it

**Comment by 3h4x** [comment]
@davidwadden 
I have rebased source code.

**Comment by davidwadden** [comment]
@3h4x we took the merge to develop,  should land on master soon

**Comment by 3h4x** [comment]
@davidwadden great! Im looking forward to see it :)

**Pull request merged**
