### PR TITLE
Handle tailing of non-existent app

### PR DESCRIPTION
**Pull request by shashidharatd**
$ltc logs non_existent_app

Used to hang indefinitely. Now it will say the app is not found.

$ltc logs non_existent_app
App not found.

### CODE REVIEW

**Comment by onsi** [comment]
hey @shashidharatd 

Thanks for the PR.  I think there's some value in being able to tail the logs *before* you create the application (ensure you don't miss any logs when the application comes up, etc...)

What if instead of `ltc logs` exiting with `App not found...` it instead said something like:

```
$ltc logs foo
Application "foo" not found.
Tailing logs and waiting for "foo" to appear...
```

and then maintained the existing behavior.

**Comment by dhilipkumars** [comment]
Thanks for the comment @onsi.  Agree with you.

Whats your opinion about

```
$ltc logs -f APP_NAME 

```

Introducing `-f` option forces tailing logs for apps yet to be created?  With a help text too? 

Also a quick question these commands do not seem to return with an error code to the shell even if they fail.

for instance 

```
$ltc logs                                  #supplied with no argument
Incorrect Usage
$echo $?
0
```
Is it by design or would you like someone to look at that?

**Comment by onsi** [comment]
Honestly, I don't see the need for the extra option.  I think if the help text is clear enough the user will know what is going on and what to do.

We have a story in our public tracker project for the exit codes:
https://www.pivotaltracker.com/story/show/87638412

**Comment by dhilipkumars** [comment]
Thanks for the clarifications.

**Comment by shashidharatd** [comment]
Hi @onsi,
  We understood the real behavior of `ltc logs` command for yet to appear app. so we just added the message as you suggested. also the test case have been modified to take care of the changes.
Along the way some more source files were changed when we did `go fmt ./...`

Also curious about the CI for this repo as there is no CI that runs when we do a PR.

**Comment by davidwadden** [comment]
Thanks for the PR !  we made a few changes around injecting the app_examiner dependency and using the AppExists method instead of AppStatus to avoid having to parse the error to determine whether the app doesn't exist or it's some other error condition.

**Pull request merged**
