### PR TITLE
Note about upgrading Vagrant for VirtualBox 5+

### LINKED ISSUE #220: Virtualbox 5.0 not supported
The latest Docker Toolbox installs Virtualbox 5.0 so when I go to start up Lattice 0.5.0 after installing Docker toolbox, I get the following error:

```
Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

### PR DESCRIPTION
**Pull request by mikegehard**
Leaving this here so that others don't jump to hasty conclusions like I did. :-)

closes #220

### CODE REVIEW

**Comment by sclevine** [comment]
Thanks for the PR! We may end up putting this on the (soon-to-be open sourced) website instead of the README. Also, active development for Lattice cluster components is moving to a different repo.

**Comment by davidwadden** [comment]
@mikegehard this got closed inadvertently while we're doing some work on our repos.  this content is moving to our website, we'll make the change and it should go out with **v0.6.0**

**Comment by damon-pivotal** [comment]
@mikegehard We've updated the website to add a note to [Troubleshooting](http://lattice.cf/docs/troubleshooting/). It's not live yet, but will go out with our upcoming release.

**Comment by mikegehard** [comment]
Thank you!

**Pull request closed without merging**
