### PR TITLE
Fix delete-task should work on a running task

### PR DESCRIPTION
**Pull request by SrinivasChilveri**
Story:https://www.pivotaltracker.com/story/show/99932696

Any suggestions/comments are welcome

### CODE REVIEW

**Comment by damon-pivotal** [comment]
@SrinivasChilveri 

Thanks for doing this, but we think there are a couple of issues with the PR.

Cancel Task is not synchronous, so it's possible that the Delete Task may execute before the task has actually been cancelled.

I think that there needs to be something in between cancel and delete which polls TaskStatus every second and waits for the task to be cancelled before proceeding with the delete. This should give up after a few seconds (maybe 30s) and fail with something like "Failed to cancel task XXXXX".

Obviously this has implications for the tests as well, since we'd want to be able to simulate these delays and failures in the unit test.

**Comment by SrinivasChilveri** [comment]
Hi @damon-pivotal , Sorry for delay in response. Thanks a lot for reply & information.I have changed as  suggested. if you have any more comments/suggestions are welcome.

Thanks & Regards,
SriniCH

**Comment by SrinivasChilveri** [comment]
Hi @damon-pivotal , Any suggestions, updates on this.

Thanks & Regards,
SriniCH

**Comment by davidwadden** [comment]
We apologize here.  We're re-arranging our repositories and Github decided to close out all the PRs when we swapped the branches.

Please go ahead and reopen this against **master** on https://github.com/cloudfoundry-incubator/ltc and we'll consider it.

**Pull request closed without merging**
