### PR TITLE
Update troubleshooting "host not found" in README

### PR DESCRIPTION
**Pull request by philwebb**
Update the troubleshooting "host not found" section of README.MD to include
details on home router DNS issues.

### CODE REVIEW

**Comment by philwebb** [comment]
@cfdreddbot @onsi Since I work for Pivotal I assume we already have a corporate CLA signed. Let me know if you need me to send some paperwork or if you can just add my GitHub user directly.

**Comment by davidwadden** [comment]
thanks @philwebb -- this landed on master with build v0.2.3-13-g6f6e0d7

**Comment by philwebb** [comment]
Thanks @davidwadden. Can I ask why you don't keep `--author` attribution when you merge commits. Not that I'm bothered personally, I'm just curious.

**Comment by davidwadden** [comment]
Whatever I did, it wasn't on purpose.  I'm a bit new to managing pull requests.  I see the PR commit is properly attributed to you, are you speaking about the merge commits?  I don't think I've tried to set author attribution to the PR submitter on the merges before.  Do you have a recommended way we should do this moving forward?

**Comment by philwebb** [comment]
Sorry, ignore me. I see 5e0446046dc79816c2fc0c6463174a1b6f25c921 is there and e4d9c819376c7c791dc8856f002c0411f300da97 is just the merge commit. I missed that when viewing the log.

Sorry for the noise.

**Pull request merged**
