### PR TITLE
Fix compile to statically link go binaries

### LINKED ISSUE #125: Unable to run healthcheck in tutum/hello-world
```bash
$ ltc create test tutum/hello-world
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 80
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 80...
No start command specified, using start command from the image metadata...
Start command is:
/bin/sh -c php-fpm -d variables_order="EGPCS" && exec nginx -g "daemon off;"
Creating App: test
26 May 14:29 [APP|0] Creating container
......26 May 14:29 [APP|0] Successfully created container
.26 May 14:29 [APP|0] [26-May-2015 11:29:09] ERROR: failed to open error_log (/var/log/php-fpm.log): Permission denied (13)
26 May 14:29 [APP|0] [26-May-2015 11:29:09] ERROR: failed to post process the configuration
26 May 14:29 [APP|0] [26-May-2015 11:29:09] ERROR: FPM initialization failed
26 May 14:29 [APP|0] Exit status 78
26 May 14:29 [APP|0] Creating container
...26 May 14:29 [APP|0] Successfully created container
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: failed to open error_log (/var/log/php-fpm.log): Permission denied (13)
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: failed to post process the configuration
26 May 14:29 [APP|0] [26-May-2015 11:29:13] ERROR: FPM initialization failed
26 May 14:29 [APP|0] Exit status 78
.26 May 14:29 [APP|0] Creating container
```

Same with `-r`:
```bash
$ ltc create test tutum/hello-world -r
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 80
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 80...
No start command specified, using start command from the image metadata...
Start command is:
/bin/sh -c php-fpm -d variables_order="EGPCS" && exec nginx -g "daemon off;"
Creating App: test
.26 May 14:30 [APP|0] Creating container
...26 May 14:30 [APP|0] Successfully created container
26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
.26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
.26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
26 May 14:30 [HEALTH|0] execvpe: No such file or directory
26 May 14:30 [HEALTH|0] Exit status 255
```

Image source:
https://github.com/tutumcloud/docker-hello-world

### PR DESCRIPTION
**Pull request by svrc**
Fixes #125

### CODE REVIEW

**Comment by davidwadden** [comment]
thanks a bunch for this -- we'll do some testing with this and ask you to rebase if we decide to merge

@davidwadden

**Comment by davidwadden** [comment]
Can you rebase this commit?

**Comment by svrc-pivotal** [comment]
no worries.  feel free to rebase it if too hard to coordinate

**Comment by damon-pivotal** [comment]
Merged in 42e5d9e4d634157662a5e3d4b9bfcf7129d7a436.

Thanks for the contribution!

**Pull request closed without merging**
