### PR TITLE
Fix the story sort numerically for ltc cells, ltc visualize

### PR DESCRIPTION
**Pull request by SrinivasChilveri**
https://www.pivotaltracker.com/story/show/104659116
https://www.pivotaltracker.com/story/show/104659106

Any comments/suggestions are welcome

### CODE REVIEW

**Comment by davidwadden** [comment]
Hey thanks for submitting this;  we're in the middle of a major refactor and aren't merging PRs at the moment, we'll take a look at this soon though.  I have this prioritized for review before our next release.

If we approve this, do you mind if we rebase the commit?

**Comment by SrinivasChilveri** [comment]
Hi @davidwadden , Its fine. if you want me to rebase & do update the PR also fine.

Thanks & Regards,
SriniCH

**Comment by ekcasey** [comment]
@SrinivasChilveri 

we took a look at this today, we have some feedback / clarification i updated onto the original story [[#104659116](https://www.pivotaltracker.com/story/show/104659116)].  the big thing we'd like is to not assume the cells are named `cell-##`, but do something less brittle like looking for `-##` (where ## is numeric) as the suffix of the cell name.

couple little things:
- add a newline between system imports and other imports at https://github.com/cloudfoundry-incubator/lattice/pull/218/files#diff-0bd23799f4357dedf54b054dc4d7922cR7
- don't need to re-define types of elements of a slice, like on https://github.com/cloudfoundry-incubator/lattice/pull/218/files#diff-7e9aa7f079e48a6081a7a1c9c672298cR252

thanks!
@davidwadden + @ekcasey

**Comment by dhilipkumars** [comment]
@ekcasey & @davidwadden 

We were trying to do two things.
1) Avoid sorting the two times.  (Decided and perform sort at ListCell )
2) We thought detecting if the last two chars are numerical might still have a case to be addressed.  For instance.
```
north-01
north-02
south-01
south-02
east-01
east-02
```
this could become 
```
north-01
south-01
east-01
north-02
south-02
east-02
```
It may be difficult to enforce the numbering if each Cell's name does not have a standard format.  IMHO we could simply stick with alphabetical ordering. 

what do you think?

**Comment by davidwadden** [comment]
You know what.  I'm totally fine with that.  I think 10+ cell deployments are kinda rare.

Thanks for looking in this with us.

FYI- we were doing some repo changes earlier which closed your PR

**Pull request closed without merging**
