### PR TITLE
Update ubuntu-trusty-64.json

### PR DESCRIPTION
**Pull request by sonoble**
Updated the file to include the version of ubuntu 14.0.4.2 available on the server along with it's matching MD5.

### CODE REVIEW

**Comment by menicosia** [comment]
Hey @snobole,

We're planning the next few weeks of releases, and issue #54 and this PR are coming up. I don't think we'll get to them in the current iteration, but we could likely schedule the work soon.

We can't accept your PR without a CLA, so if you'd like to go forward with that, we can merge this PR when ready. Otherwise, we'll probably duplicate your work separate from this PR.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by davidwadden** [comment]
@sonoble, we're planning to pull this in next week.  if you'd like us to merge this, please sign the cla and rebase your branch to resolve the conflicts.

thanks!
david

**Comment by sonoble** [comment]
Hi David,

My CLA has been accepted, let me sort out the rebasing.  I dislike
github as it forks everything so it always takes me a minute to remember
how to deal with how github works :)

**Comment by davidwadden** [comment]
great! 

```
git checkout patch-1
git remote add upstream git@github.com:cloudfoundry-incubator/lattice.git
git rebase upstream/master  # or develop
git push --force
```

or something like that

**Comment by sonoble** [comment]
Done!

**Comment by davidwadden** [comment]
@sonoble we took the merge to develop,  should land on master soon

**Pull request merged**
