### PR TITLE
ltc visualize -r=<time.Duration>

### PR DESCRIPTION
**Pull request by dhilipkumars**
Hi 

Here is the initial commit to get a quick feed back. 

when we type  visualize command with rate flag like below it goes to a brand new screen that animates.  (vz command without rate flag retains the original behaviour)

```
$ltc vz -r=1s
```

image

**Explanation:**
1) Left most green bar is the Y-Axis representing percentage
2) Each bar afterwards is a lattice cell that represents how much has it progressed. (in percentage) 
3) Under each bar (X-Axis) we have Lattice Cell Index [ Running Instance/Total expected Instance]
4) If a cell has no Claimed Instance and all Running Instance then it is 100%

**Features:**
hit q to exit the graphic screen
hit + to incrase the refresh rate
hit - to decrese the refresh rate
it aligns to an extent with terminal resize.

**Problem**
I have not found a way to add unit test yet as this is terminal screen buffer (graphical) and not text mode.  :-(  Any clue would be great. 

Please feel free to reject as i can get a proper PR via my organization with the suggestions included. 
The only intention is to find out if im in track. 

PS: Please dont mind the godep noise the actual changes is only in app_examiner_command_factory.go

### CODE REVIEW

**Comment by davidwadden** [comment]
@dhilipkumars -- we'll take a look at this and give you some feedback soon

**Comment by dhilipkumars** [comment]
Have raised a PR to termui https://github.com/gizak/termui/pull/28, if its merged we wont need the Y-Axis reference bar (left most one).  

We can change the title `Lattice Equalizer` just like the music players. ;-) implying lattice will try to equalize the load among cells.

**Comment by davidwadden** [comment]
we tried out this PR this morning.  i think the termui library has some great features we could take advantage of for our `ltc visualize` command, but i feel the current state of the PR provides limited value.  Aside from the starting/stopping apps, the visualize output shows a full column for each cell the rest of the time.

1) `ltc visualize` should look the same for now, with a `--graphical` option to display the termui version.  Not sure if you want to support the non-refresh mode, or basically require --rate also be passed along with with --graphical
2) desired app instances should be colored something other than black, but i understand it's hard to display absolute metrics such as 7 app instances running on a cell.  do you have any ideas how we could show cell 1 is running 4 app instances and cell 2 is running 7 app instances and not just showing a filled column showing 100% of desired instances on a cell are running?  Maybe normalize y-axis against max(desired) across all cells? 
3) There's a feature coming down the pike [story](https://www.pivotaltracker.com/story/show/90241710) that will show cpu/memory/disk utilization per instance, this would be a great way to display all that data once that's implemented.  Maybe think ahead how would make sense to organize this data onto one screen.

let us know if you have any questions, we really appreciate your contributions and are happy to provide feedback on the design for this

**Comment by dhilipkumars** [comment]
@davidwadden   Thanks very much for trying out the PR.  :-)  

1) Will change accordingly .  We can optionally take a -rate flag along with -graphical, if not specified we can default to 1s (rate can be adjusted within the graphical screen anyways)

2) 
a) The current bar.go in termui has only one that can be specified as the bar color.  I'm thinking of contributing more features to termui so that multi-color or at-least dual color bar graphs be plotted.
b) Yes we can set Y.Axis's maximum value as Max(running+claimed) among all the cells so the we can differentiate between which one has more instances and which one has less instances. `termui team was kind enough to accept my patch so now we can get rid of the Y-Axis reference bar`

3) Yes the story seems interesting, i would love to implement it.  I have an idea.  How about `F1`, `F2` keys be used to switch between two screens? 
`F1` :- Default bargrpah with cell wise (app distribution)  [Default]
`F2` :- Cell wise Memory/Disk utilization.   (if possible CPU utilization)
We may not be able to plot instance wise data as, we may not have that many colors to represent if lattices is loaded with 10's or 100's of different apps.  For now a cell wise consolidated looks feasible to me. 

If you are okay i could send in a PR that works for `F1` and later we can add the `F2` screen as an additional feature as soon as the above mentioned story is implemented.  Is that okay?

Also any hint/clue on how i could write unit-tests for this would be really great.

**Comment by dhilipkumars** [comment]
A quick update: A [PR](https://github.com/gizak/termui/pull/31) is underway with termui to plot BarGraphs with multi-colors.  If it gets merged, we will have everything we need to visualize lattice. :-) I can raise one  by Monday that works for F1 will all your suggestions incorporated.

**Pull request closed without merging**
