### PR TITLE
Introduce -g option for ltc visualize command

### PR DESCRIPTION
**Pull request by dhilipkumars**
Hi

Ltc visualize now has an additional option to visualize in a light wight grpahical mode

```
ltc help vz
NAME:
   visualize - Shows a visualization of the workload distribution across the lattice cells

USAGE:
   command visualize [command options] [arguments...]

DESCRIPTION:
   ltc visualize [-r=DELAY] [-g]

OPTIONS:
   --rate, -r "0"       Visualization refresh rate (e.g., ".5s" or "10ms")
   --graphical, -g      Visualize in a graphical screen
```

When we type -graphical optoin it now displays like below for a single cell instance, yello portion is claimed and green portion is running instances.

temp1

A simulated multi-cell output

temp2

it optionally takes a 'rate' argument, which can also be adjusted from within the terminal window by hitting `+` to increase and `-` to decrese the refresh rate.

This includes temui in godeps directory structure.

### CODE REVIEW

**Comment by davidwadden** [comment]
this is pretty dang cool.  we took a look at it today,  i think we'll accept the merge tomorrow ..

thanks again!
david

**Comment by dhilipkumars** [comment]
@davidwadden  thank you very much for trying it out. :-) Ill be very glad seeing it merged. termui team was kind enough to accept our merge.

**Comment by davidwadden** [comment]
@dhilipkumars - We accepted the PR this morning and made a couple minor tweaks around changing the increment to 100ms instead of 1second.  I think that sub-second refresh rates are pretty useful to demonstrate some of the mechanics of the runtime.

I have some feedback around some follow-ups we'd love to see on this functionality.  I know you asked us for some advice on what we'd be looking for regarding testing and I didn't answer that, but I think what makes sense is to break out the presentation-specific logic into its own package (something like `graphical` under the `app_examiner_command_factory`) that we don't test, and then create a couple new tests when the `--graphical` flag is passed: one when `printDistributionChart()` succeeds and one when it returns an error.

Then, here's a bit of a brain dump around some other things I noticed when testing this:


* CellID does not match actual cell id, instead looks like some sequence variable
  - This becomes noticable > 10 cells, when it looks like `appExaminer.ListCells()` is ordering them alphabetically (cell-1, cell-10, cell-11, cell-2), but `ltc visualize -g` is listing them 1,2,3,4.
  - Would probably require chopping `cell-` off of the CellName, then not sure whether we should 0-pad on the cluster side (e.g., cell-01, cell-02, and we would do this) , or have `ltc` do the Atoi conversion (somewhat brittle, if somehow that string isn't formatted "cell-##")
* Center-align cell labels
  - There's not much space, especially when you get to cells 10+, but it's noticable when a cell is empty or missing

image

* Some kind of Y-Axis scale label ?  The running/desired instances counter on each bar is good, but when the graph re-normalizes, I think would be helpful to see some kind of scale without having to read.

If you're interested in continuing to work on this, feel free to contact us.

**Comment by dhilipkumars** [comment]
@davidwadden thanks again for the merge and the feedback. :-)
My current dev environment does not have multi-cell setup so had to simulate it with some ugly hack like this in `app_examiner.go` while testing :-(

```
func (e *appExaminer) FakeListCells() ([]CellInfo, error) {
	allCells := make(map[string]*CellInfo)
	
	
	n := rand.Intn(10) + 1
	
	for i:=1; i<n; i++ {
		cellname := fmt.Sprintf("Cell:%d", i)
		allCells[cellname] = &CellInfo{CellID: cellname, RunningInstances : rand.Intn(100)+1, ClaimedInstances : rand.Intn(100)+1}
	}

	return sortCells(allCells), nil
}
```

which is why i could not see these problems, we are working to get a multi-Cell setup in parallel. 

We would be more than happy to implement all your suggestions and send you a PR very soon for review.

**Comment by dhilipkumars** [comment]
@davidwadden Quick update,
1) A [PR](https://github.com/HuaweiTech/lattice/pull/9/files) implementing all your suggestions is ready.
2) A [PR](https://github.com/gizak/termui/pull/40) to termui implementing Y-Axis scale indication and centering label has been raised.

After an internal review and syncing termui to the latest `(if its merged tonight)` we should be able to send you the PR CF team for review by tommorow.

**Pull request merged**
